export enum CommandBlockFlags {
    TrackOutput = 0x01,
    IsConditional = 0x02,
    Automatic = 0x04,
}

export enum CommandBlockMode {
    Sequence = 0,
    Auto = 1,
    Redstone = 2,
}

export enum Direction {
    South = 0,
    West = 1,
    North = 2,
    East = 3,

    Up = 4,
    Down = 5,

    NorthEast = 6,
    SouthEast = 7,
    SouthWest = 8,
    NorthWest = 9,
}

export enum EntityType {
    AreaEffectCloud,
    ArmorStand,
    Arrow,
    Axolotl,
    Bat,
    Bee,
    Blaze,
    Boat,
    Cat,
    CaveSpider,
    ChestMinecart,
    Chicken,
    Cod,
    CommandBlockMinecart,
    Cow,
    Creeper,
    Dolphin,
    Donkey,
    DragonFireball,
    Drowned,
    Egg,
    ElderGuardian,
    EndCrystal,
    EnderDragon,
    Enderman,
    Endermite,
    EnderPearl,
    Evoker,
    EvokerFangs,
    ExperienceBottle,
    ExperienceOrb,
    EyeOfEnder,
    FallingBlock,
    Fireball,
    FireworkRocket,
    FishingBobber,
    Fox,
    FurnaceMinecart,
    Ghast,
    Giant,
    GlowItemFrame,
    GlowSquid,
    Goat,
    Guardian,
    Hoglin,
    HopperMinecart,
    Horse,
    Husk,
    Illusioner,
    IronGolem,
    Item,
    ItemFrame,
    LeashKnot,
    LightningBolt,
    Llama,
    LlamaSpit,
    MagmaCube,
    Marker,
    Minecart,
    Mooshroom,
    Mule,
    Ocelot,
    Painting,
    Panda,
    Parrot,
    Phantom,
    Pig,
    Piglin,
    PiglinBrute,
    Pillager,
    Player,
    PolarBear,
    Potion,
    Pufferfish,
    Rabbit,
    Ravager,
    Salmon,
    Sheep,
    Shulker,
    ShulkerBullet,
    Silverfish,
    Skeleton,
    SkeletonHorse,
    Slime,
    SmallFireball,
    Snowball,
    SnowGolem,
    SpawnerMinecart,
    SpectralArrow,
    Spider,
    Squid,
    Stray,
    Strider,
    Tnt,
    TntMinecart,
    TraderLlama,
    Trident,
    TropicalFish,
    Turtle,
    Vex,
    Villager,
    Vindicator,
    WanderingTrader,
    Witch,
    Wither,
    WitherSkeleton,
    WitherSkull,
    Wolf,
    Zoglin,
    Zombie,
    ZombieHorse,
    ZombieVillager,
    ZombifiedPiglin,
}

export enum EntityPose {
    Standing = 0,
    FallFlying = 1,
    Sleeping = 2,
    Swimming = 3,
    SpinAttack = 4,
    Sneaking = 5,
    Dying = 6,
};

export type Entity = {
    ID: number,
    UUID: string,
    Name?: string,
    CustomNameJson: string,
    IsCustomNameVisible: boolean,
    CustomName: string,
    Latency: number,
    Type: EntityType,
    Location: Location,
    Yaw: number,
    Pitch: number,
    ObjectData: number,
    Health: number,
    Item: Item,
    Pose: EntityPose,
    Metadata: any,
    Equipment: any,

};

export enum EntityActionType {
    StartSneaking = 0,
    StopSneaking = 1,
    LeaveBed = 2,
    StartSprinting = 3,
    StopSprinting = 4,
    StartJumpWithHorse = 5,
    StopJumpWithHorse = 6,
    OpenHorseInventory = 7,
    StartFlyingWithElytra = 8,
}

export enum Hand {
    MainHand = 0,
    OffHand = 1,
}

export enum InteractType {
    Interact = 0,
    Attack,
    InteractAt
}

export enum ItemType {
    Unknown = -2, // Unsupported item type (Forge mod custom item...)
    Null = -1,    // Unspecified item type (Used in the network protocol)

    AcaciaBoat,
    AcaciaButton,
    AcaciaDoor,
    AcaciaFence,
    AcaciaFenceGate,
    AcaciaLeaves,
    AcaciaLog,
    AcaciaPlanks,
    AcaciaPressurePlate,
    AcaciaSapling,
    AcaciaSign,
    AcaciaSlab,
    AcaciaStairs,
    AcaciaTrapdoor,
    AcaciaWood,
    ActivatorRail,
    Air,
    Allium,
    AmethystBlock,
    AmethystCluster,
    AmethystShard,
    AncientDebris,
    Andesite,
    AndesiteSlab,
    AndesiteStairs,
    AndesiteWall,
    Anvil,
    Apple,
    ArmorStand,
    Arrow,
    AxolotlBucket,
    AxolotlSpawnEgg,
    Azalea,
    AzaleaLeaves,
    AzureBluet,
    BakedPotato,
    Bamboo,
    Barrel,
    Barrier,
    Basalt,
    BatSpawnEgg,
    Beacon,
    Bedrock,
    BeeNest,
    BeeSpawnEgg,
    Beef,
    Beehive,
    Beetroot,
    BeetrootSeeds,
    BeetrootSoup,
    Bell,
    BigDripleaf,
    BirchBoat,
    BirchButton,
    BirchDoor,
    BirchFence,
    BirchFenceGate,
    BirchLeaves,
    BirchLog,
    BirchPlanks,
    BirchPressurePlate,
    BirchSapling,
    BirchSign,
    BirchSlab,
    BirchStairs,
    BirchTrapdoor,
    BirchWood,
    BlackBanner,
    BlackBed,
    BlackCandle,
    BlackCarpet,
    BlackConcrete,
    BlackConcretePowder,
    BlackDye,
    BlackGlazedTerracotta,
    BlackShulkerBox,
    BlackStainedGlass,
    BlackStainedGlassPane,
    BlackTerracotta,
    BlackWool,
    Blackstone,
    BlackstoneSlab,
    BlackstoneStairs,
    BlackstoneWall,
    BlastFurnace,
    BlazePowder,
    BlazeRod,
    BlazeSpawnEgg,
    BlueBanner,
    BlueBed,
    BlueCandle,
    BlueCarpet,
    BlueConcrete,
    BlueConcretePowder,
    BlueDye,
    BlueGlazedTerracotta,
    BlueIce,
    BlueOrchid,
    BlueShulkerBox,
    BlueStainedGlass,
    BlueStainedGlassPane,
    BlueTerracotta,
    BlueWool,
    Bone,
    BoneBlock,
    BoneMeal,
    Book,
    Bookshelf,
    Bow,
    Bowl,
    BrainCoral,
    BrainCoralBlock,
    BrainCoralFan,
    Bread,
    BrewingStand,
    Brick,
    BrickSlab,
    BrickStairs,
    BrickWall,
    Bricks,
    BrownBanner,
    BrownBed,
    BrownCandle,
    BrownCarpet,
    BrownConcrete,
    BrownConcretePowder,
    BrownDye,
    BrownGlazedTerracotta,
    BrownMushroom,
    BrownMushroomBlock,
    BrownShulkerBox,
    BrownStainedGlass,
    BrownStainedGlassPane,
    BrownTerracotta,
    BrownWool,
    BubbleCoral,
    BubbleCoralBlock,
    BubbleCoralFan,
    Bucket,
    BuddingAmethyst,
    Bundle,
    Cactus,
    Cake,
    Calcite,
    Campfire,
    Candle,
    Carrot,
    CarrotOnAStick,
    CartographyTable,
    CarvedPumpkin,
    CatSpawnEgg,
    Cauldron,
    CaveSpiderSpawnEgg,
    Chain,
    ChainCommandBlock,
    ChainmailBoots,
    ChainmailChestplate,
    ChainmailHelmet,
    ChainmailLeggings,
    Charcoal,
    Chest,
    ChestMinecart,
    Chicken,
    ChickenSpawnEgg,
    ChippedAnvil,
    ChiseledDeepslate,
    ChiseledNetherBricks,
    ChiseledPolishedBlackstone,
    ChiseledQuartzBlock,
    ChiseledRedSandstone,
    ChiseledSandstone,
    ChiseledStoneBricks,
    ChorusFlower,
    ChorusFruit,
    ChorusPlant,
    Clay,
    ClayBall,
    Clock,
    Coal,
    CoalBlock,
    CoalOre,
    CoarseDirt,
    CobbledDeepslate,
    CobbledDeepslateSlab,
    CobbledDeepslateStairs,
    CobbledDeepslateWall,
    Cobblestone,
    CobblestoneSlab,
    CobblestoneStairs,
    CobblestoneWall,
    Cobweb,
    CocoaBeans,
    Cod,
    CodBucket,
    CodSpawnEgg,
    CommandBlock,
    CommandBlockMinecart,
    Comparator,
    Compass,
    Composter,
    Conduit,
    CookedBeef,
    CookedChicken,
    CookedCod,
    CookedMutton,
    CookedPorkchop,
    CookedRabbit,
    CookedSalmon,
    Cookie,
    CopperBlock,
    CopperIngot,
    CopperOre,
    Cornflower,
    CowSpawnEgg,
    CrackedDeepslateBricks,
    CrackedDeepslateTiles,
    CrackedNetherBricks,
    CrackedPolishedBlackstoneBricks,
    CrackedStoneBricks,
    CraftingTable,
    CreeperBannerPattern,
    CreeperHead,
    CreeperSpawnEgg,
    CrimsonButton,
    CrimsonDoor,
    CrimsonFence,
    CrimsonFenceGate,
    CrimsonFungus,
    CrimsonHyphae,
    CrimsonNylium,
    CrimsonPlanks,
    CrimsonPressurePlate,
    CrimsonRoots,
    CrimsonSign,
    CrimsonSlab,
    CrimsonStairs,
    CrimsonStem,
    CrimsonTrapdoor,
    Crossbow,
    CryingObsidian,
    CutCopper,
    CutCopperSlab,
    CutCopperStairs,
    CutRedSandstone,
    CutRedSandstoneSlab,
    CutSandstone,
    CutSandstoneSlab,
    CyanBanner,
    CyanBed,
    CyanCandle,
    CyanCarpet,
    CyanConcrete,
    CyanConcretePowder,
    CyanDye,
    CyanGlazedTerracotta,
    CyanShulkerBox,
    CyanStainedGlass,
    CyanStainedGlassPane,
    CyanTerracotta,
    CyanWool,
    DamagedAnvil,
    Dandelion,
    DarkOakBoat,
    DarkOakButton,
    DarkOakDoor,
    DarkOakFence,
    DarkOakFenceGate,
    DarkOakLeaves,
    DarkOakLog,
    DarkOakPlanks,
    DarkOakPressurePlate,
    DarkOakSapling,
    DarkOakSign,
    DarkOakSlab,
    DarkOakStairs,
    DarkOakTrapdoor,
    DarkOakWood,
    DarkPrismarine,
    DarkPrismarineSlab,
    DarkPrismarineStairs,
    DaylightDetector,
    DeadBrainCoral,
    DeadBrainCoralBlock,
    DeadBrainCoralFan,
    DeadBubbleCoral,
    DeadBubbleCoralBlock,
    DeadBubbleCoralFan,
    DeadBush,
    DeadFireCoral,
    DeadFireCoralBlock,
    DeadFireCoralFan,
    DeadHornCoral,
    DeadHornCoralBlock,
    DeadHornCoralFan,
    DeadTubeCoral,
    DeadTubeCoralBlock,
    DeadTubeCoralFan,
    DebugStick,
    Deepslate,
    DeepslateBrickSlab,
    DeepslateBrickStairs,
    DeepslateBrickWall,
    DeepslateBricks,
    DeepslateCoalOre,
    DeepslateCopperOre,
    DeepslateDiamondOre,
    DeepslateEmeraldOre,
    DeepslateGoldOre,
    DeepslateIronOre,
    DeepslateLapisOre,
    DeepslateRedstoneOre,
    DeepslateTileSlab,
    DeepslateTileStairs,
    DeepslateTileWall,
    DeepslateTiles,
    DetectorRail,
    Diamond,
    DiamondAxe,
    DiamondBlock,
    DiamondBoots,
    DiamondChestplate,
    DiamondHelmet,
    DiamondHoe,
    DiamondHorseArmor,
    DiamondLeggings,
    DiamondOre,
    DiamondPickaxe,
    DiamondShovel,
    DiamondSword,
    Diorite,
    DioriteSlab,
    DioriteStairs,
    DioriteWall,
    Dirt,
    Dispenser,
    DolphinSpawnEgg,
    DonkeySpawnEgg,
    DragonBreath,
    DragonEgg,
    DragonHead,
    DriedKelp,
    DriedKelpBlock,
    DripstoneBlock,
    Dropper,
    DrownedSpawnEgg,
    Egg,
    ElderGuardianSpawnEgg,
    Elytra,
    Emerald,
    EmeraldBlock,
    EmeraldOre,
    EnchantedBook,
    EnchantedGoldenApple,
    EnchantingTable,
    EndCrystal,
    EndPortalFrame,
    EndRod,
    EndStone,
    EndStoneBrickSlab,
    EndStoneBrickStairs,
    EndStoneBrickWall,
    EndStoneBricks,
    EnderChest,
    EnderEye,
    EnderPearl,
    EndermanSpawnEgg,
    EndermiteSpawnEgg,
    EvokerSpawnEgg,
    ExperienceBottle,
    ExposedCopper,
    ExposedCutCopper,
    ExposedCutCopperSlab,
    ExposedCutCopperStairs,
    Farmland,
    Feather,
    FermentedSpiderEye,
    Fern,
    FilledMap,
    FireCharge,
    FireCoral,
    FireCoralBlock,
    FireCoralFan,
    FireworkRocket,
    FireworkStar,
    FishingRod,
    FletchingTable,
    Flint,
    FlintAndSteel,
    FlowerBannerPattern,
    FlowerPot,
    FloweringAzalea,
    FloweringAzaleaLeaves,
    FoxSpawnEgg,
    Furnace,
    FurnaceMinecart,
    GhastSpawnEgg,
    GhastTear,
    GildedBlackstone,
    Glass,
    GlassBottle,
    GlassPane,
    GlisteringMelonSlice,
    GlobeBannerPattern,
    GlowBerries,
    GlowInkSac,
    GlowItemFrame,
    GlowLichen,
    GlowSquidSpawnEgg,
    Glowstone,
    GlowstoneDust,
    GoatSpawnEgg,
    GoldBlock,
    GoldIngot,
    GoldNugget,
    GoldOre,
    GoldenApple,
    GoldenAxe,
    GoldenBoots,
    GoldenCarrot,
    GoldenChestplate,
    GoldenHelmet,
    GoldenHoe,
    GoldenHorseArmor,
    GoldenLeggings,
    GoldenPickaxe,
    GoldenShovel,
    GoldenSword,
    Granite,
    GraniteSlab,
    GraniteStairs,
    GraniteWall,
    Grass,
    GrassBlock,
    GrassPath,
    Gravel,
    GrayBanner,
    GrayBed,
    GrayCandle,
    GrayCarpet,
    GrayConcrete,
    GrayConcretePowder,
    GrayDye,
    GrayGlazedTerracotta,
    GrayShulkerBox,
    GrayStainedGlass,
    GrayStainedGlassPane,
    GrayTerracotta,
    GrayWool,
    GreenBanner,
    GreenBed,
    GreenCandle,
    GreenCarpet,
    GreenConcrete,
    GreenConcretePowder,
    GreenDye,
    GreenGlazedTerracotta,
    GreenShulkerBox,
    GreenStainedGlass,
    GreenStainedGlassPane,
    GreenTerracotta,
    GreenWool,
    Grindstone,
    GuardianSpawnEgg,
    Gunpowder,
    HangingRoots,
    HayBlock,
    HeartOfTheSea,
    HeavyWeightedPressurePlate,
    HoglinSpawnEgg,
    HoneyBlock,
    HoneyBottle,
    Honeycomb,
    HoneycombBlock,
    Hopper,
    HopperMinecart,
    HornCoral,
    HornCoralBlock,
    HornCoralFan,
    HorseSpawnEgg,
    HuskSpawnEgg,
    Ice,
    InfestedChiseledStoneBricks,
    InfestedCobblestone,
    InfestedCrackedStoneBricks,
    InfestedDeepslate,
    InfestedMossyStoneBricks,
    InfestedStone,
    InfestedStoneBricks,
    InkSac,
    IronAxe,
    IronBars,
    IronBlock,
    IronBoots,
    IronChestplate,
    IronDoor,
    IronHelmet,
    IronHoe,
    IronHorseArmor,
    IronIngot,
    IronLeggings,
    IronNugget,
    IronOre,
    IronPickaxe,
    IronShovel,
    IronSword,
    IronTrapdoor,
    ItemFrame,
    JackOLantern,
    Jigsaw,
    Jukebox,
    JungleBoat,
    JungleButton,
    JungleDoor,
    JungleFence,
    JungleFenceGate,
    JungleLeaves,
    JungleLog,
    JunglePlanks,
    JunglePressurePlate,
    JungleSapling,
    JungleSign,
    JungleSlab,
    JungleStairs,
    JungleTrapdoor,
    JungleWood,
    Kelp,
    KnowledgeBook,
    Ladder,
    Lantern,
    LapisBlock,
    LapisLazuli,
    LapisOre,
    LargeAmethystBud,
    LargeFern,
    LavaBucket,
    Lead,
    Leather,
    LeatherBoots,
    LeatherChestplate,
    LeatherHelmet,
    LeatherHorseArmor,
    LeatherLeggings,
    Lectern,
    Lever,
    Light,
    LightBlueBanner,
    LightBlueBed,
    LightBlueCandle,
    LightBlueCarpet,
    LightBlueConcrete,
    LightBlueConcretePowder,
    LightBlueDye,
    LightBlueGlazedTerracotta,
    LightBlueShulkerBox,
    LightBlueStainedGlass,
    LightBlueStainedGlassPane,
    LightBlueTerracotta,
    LightBlueWool,
    LightGrayBanner,
    LightGrayBed,
    LightGrayCandle,
    LightGrayCarpet,
    LightGrayConcrete,
    LightGrayConcretePowder,
    LightGrayDye,
    LightGrayGlazedTerracotta,
    LightGrayShulkerBox,
    LightGrayStainedGlass,
    LightGrayStainedGlassPane,
    LightGrayTerracotta,
    LightGrayWool,
    LightWeightedPressurePlate,
    LightningRod,
    Lilac,
    LilyOfTheValley,
    LilyPad,
    LimeBanner,
    LimeBed,
    LimeCandle,
    LimeCarpet,
    LimeConcrete,
    LimeConcretePowder,
    LimeDye,
    LimeGlazedTerracotta,
    LimeShulkerBox,
    LimeStainedGlass,
    LimeStainedGlassPane,
    LimeTerracotta,
    LimeWool,
    LingeringPotion,
    LlamaSpawnEgg,
    Lodestone,
    Loom,
    MagentaBanner,
    MagentaBed,
    MagentaCandle,
    MagentaCarpet,
    MagentaConcrete,
    MagentaConcretePowder,
    MagentaDye,
    MagentaGlazedTerracotta,
    MagentaShulkerBox,
    MagentaStainedGlass,
    MagentaStainedGlassPane,
    MagentaTerracotta,
    MagentaWool,
    MagmaBlock,
    MagmaCream,
    MagmaCubeSpawnEgg,
    Map,
    MediumAmethystBud,
    Melon,
    MelonSeeds,
    MelonSlice,
    MilkBucket,
    Minecart,
    MojangBannerPattern,
    MooshroomSpawnEgg,
    MossBlock,
    MossCarpet,
    MossyCobblestone,
    MossyCobblestoneSlab,
    MossyCobblestoneStairs,
    MossyCobblestoneWall,
    MossyStoneBrickSlab,
    MossyStoneBrickStairs,
    MossyStoneBrickWall,
    MossyStoneBricks,
    MuleSpawnEgg,
    MushroomStem,
    MushroomStew,
    MusicDisc11,
    MusicDisc13,
    MusicDiscBlocks,
    MusicDiscCat,
    MusicDiscChirp,
    MusicDiscFar,
    MusicDiscMall,
    MusicDiscMellohi,
    MusicDiscOtherside,
    MusicDiscPigstep,
    MusicDiscStal,
    MusicDiscStrad,
    MusicDiscWait,
    MusicDiscWard,
    Mutton,
    Mycelium,
    NameTag,
    NautilusShell,
    NetherBrick,
    NetherBrickFence,
    NetherBrickSlab,
    NetherBrickStairs,
    NetherBrickWall,
    NetherBricks,
    NetherGoldOre,
    NetherQuartzOre,
    NetherSprouts,
    NetherStar,
    NetherWart,
    NetherWartBlock,
    NetheriteAxe,
    NetheriteBlock,
    NetheriteBoots,
    NetheriteChestplate,
    NetheriteHelmet,
    NetheriteHoe,
    NetheriteIngot,
    NetheriteLeggings,
    NetheritePickaxe,
    NetheriteScrap,
    NetheriteShovel,
    NetheriteSword,
    Netherrack,
    NoteBlock,
    OakBoat,
    OakButton,
    OakDoor,
    OakFence,
    OakFenceGate,
    OakLeaves,
    OakLog,
    OakPlanks,
    OakPressurePlate,
    OakSapling,
    OakSign,
    OakSlab,
    OakStairs,
    OakTrapdoor,
    OakWood,
    Observer,
    Obsidian,
    OcelotSpawnEgg,
    OrangeBanner,
    OrangeBed,
    OrangeCandle,
    OrangeCarpet,
    OrangeConcrete,
    OrangeConcretePowder,
    OrangeDye,
    OrangeGlazedTerracotta,
    OrangeShulkerBox,
    OrangeStainedGlass,
    OrangeStainedGlassPane,
    OrangeTerracotta,
    OrangeTulip,
    OrangeWool,
    OxeyeDaisy,
    OxidizedCopper,
    OxidizedCutCopper,
    OxidizedCutCopperSlab,
    OxidizedCutCopperStairs,
    PackedIce,
    Painting,
    PandaSpawnEgg,
    Paper,
    ParrotSpawnEgg,
    Peony,
    PetrifiedOakSlab,
    PhantomMembrane,
    PhantomSpawnEgg,
    PigSpawnEgg,
    PiglinBannerPattern,
    PiglinBruteSpawnEgg,
    PiglinSpawnEgg,
    PillagerSpawnEgg,
    PinkBanner,
    PinkBed,
    PinkCandle,
    PinkCarpet,
    PinkConcrete,
    PinkConcretePowder,
    PinkDye,
    PinkGlazedTerracotta,
    PinkShulkerBox,
    PinkStainedGlass,
    PinkStainedGlassPane,
    PinkTerracotta,
    PinkTulip,
    PinkWool,
    Piston,
    PlayerHead,
    Podzol,
    PointedDripstone,
    PoisonousPotato,
    PolarBearSpawnEgg,
    PolishedAndesite,
    PolishedAndesiteSlab,
    PolishedAndesiteStairs,
    PolishedBasalt,
    PolishedBlackstone,
    PolishedBlackstoneBrickSlab,
    PolishedBlackstoneBrickStairs,
    PolishedBlackstoneBrickWall,
    PolishedBlackstoneBricks,
    PolishedBlackstoneButton,
    PolishedBlackstonePressurePlate,
    PolishedBlackstoneSlab,
    PolishedBlackstoneStairs,
    PolishedBlackstoneWall,
    PolishedDeepslate,
    PolishedDeepslateSlab,
    PolishedDeepslateStairs,
    PolishedDeepslateWall,
    PolishedDiorite,
    PolishedDioriteSlab,
    PolishedDioriteStairs,
    PolishedGranite,
    PolishedGraniteSlab,
    PolishedGraniteStairs,
    PoppedChorusFruit,
    Poppy,
    Porkchop,
    Potato,
    Potion,
    PowderSnowBucket,
    PoweredRail,
    Prismarine,
    PrismarineBrickSlab,
    PrismarineBrickStairs,
    PrismarineBricks,
    PrismarineCrystals,
    PrismarineShard,
    PrismarineSlab,
    PrismarineStairs,
    PrismarineWall,
    Pufferfish,
    PufferfishBucket,
    PufferfishSpawnEgg,
    Pumpkin,
    PumpkinPie,
    PumpkinSeeds,
    PurpleBanner,
    PurpleBed,
    PurpleCandle,
    PurpleCarpet,
    PurpleConcrete,
    PurpleConcretePowder,
    PurpleDye,
    PurpleGlazedTerracotta,
    PurpleShulkerBox,
    PurpleStainedGlass,
    PurpleStainedGlassPane,
    PurpleTerracotta,
    PurpleWool,
    PurpurBlock,
    PurpurPillar,
    PurpurSlab,
    PurpurStairs,
    Quartz,
    QuartzBlock,
    QuartzBricks,
    QuartzPillar,
    QuartzSlab,
    QuartzStairs,
    Rabbit,
    RabbitFoot,
    RabbitHide,
    RabbitSpawnEgg,
    RabbitStew,
    Rail,
    RavagerSpawnEgg,
    RawCopper,
    RawCopperBlock,
    RawGold,
    RawGoldBlock,
    RawIron,
    RawIronBlock,
    RedBanner,
    RedBed,
    RedCandle,
    RedCarpet,
    RedConcrete,
    RedConcretePowder,
    RedDye,
    RedGlazedTerracotta,
    RedMushroom,
    RedMushroomBlock,
    RedNetherBrickSlab,
    RedNetherBrickStairs,
    RedNetherBrickWall,
    RedNetherBricks,
    RedSand,
    RedSandstone,
    RedSandstoneSlab,
    RedSandstoneStairs,
    RedSandstoneWall,
    RedShulkerBox,
    RedStainedGlass,
    RedStainedGlassPane,
    RedTerracotta,
    RedTulip,
    RedWool,
    Redstone,
    RedstoneBlock,
    RedstoneLamp,
    RedstoneOre,
    RedstoneTorch,
    Repeater,
    RepeatingCommandBlock,
    RespawnAnchor,
    RootedDirt,
    RoseBush,
    RottenFlesh,
    Saddle,
    Salmon,
    SalmonBucket,
    SalmonSpawnEgg,
    Sand,
    Sandstone,
    SandstoneSlab,
    SandstoneStairs,
    SandstoneWall,
    Scaffolding,
    SculkSensor,
    Scute,
    SeaLantern,
    SeaPickle,
    Seagrass,
    Shears,
    SheepSpawnEgg,
    Shield,
    Shroomlight,
    ShulkerBox,
    ShulkerShell,
    ShulkerSpawnEgg,
    SilverfishSpawnEgg,
    SkeletonHorseSpawnEgg,
    SkeletonSkull,
    SkeletonSpawnEgg,
    SkullBannerPattern,
    SlimeBall,
    SlimeBlock,
    SlimeSpawnEgg,
    SmallAmethystBud,
    SmallDripleaf,
    SmithingTable,
    Smoker,
    SmoothBasalt,
    SmoothQuartz,
    SmoothQuartzSlab,
    SmoothQuartzStairs,
    SmoothRedSandstone,
    SmoothRedSandstoneSlab,
    SmoothRedSandstoneStairs,
    SmoothSandstone,
    SmoothSandstoneSlab,
    SmoothSandstoneStairs,
    SmoothStone,
    SmoothStoneSlab,
    Snow,
    SnowBlock,
    Snowball,
    SoulCampfire,
    SoulLantern,
    SoulSand,
    SoulSoil,
    SoulTorch,
    Spawner,
    SpectralArrow,
    SpiderEye,
    SpiderSpawnEgg,
    SplashPotion,
    Sponge,
    SporeBlossom,
    SpruceBoat,
    SpruceButton,
    SpruceDoor,
    SpruceFence,
    SpruceFenceGate,
    SpruceLeaves,
    SpruceLog,
    SprucePlanks,
    SprucePressurePlate,
    SpruceSapling,
    SpruceSign,
    SpruceSlab,
    SpruceStairs,
    SpruceTrapdoor,
    SpruceWood,
    Spyglass,
    SquidSpawnEgg,
    Stick,
    StickyPiston,
    Stone,
    StoneAxe,
    StoneBrickSlab,
    StoneBrickStairs,
    StoneBrickWall,
    StoneBricks,
    StoneButton,
    StoneHoe,
    StonePickaxe,
    StonePressurePlate,
    StoneShovel,
    StoneSlab,
    StoneStairs,
    StoneSword,
    Stonecutter,
    StraySpawnEgg,
    StriderSpawnEgg,
    String,
    StrippedAcaciaLog,
    StrippedAcaciaWood,
    StrippedBirchLog,
    StrippedBirchWood,
    StrippedCrimsonHyphae,
    StrippedCrimsonStem,
    StrippedDarkOakLog,
    StrippedDarkOakWood,
    StrippedJungleLog,
    StrippedJungleWood,
    StrippedOakLog,
    StrippedOakWood,
    StrippedSpruceLog,
    StrippedSpruceWood,
    StrippedWarpedHyphae,
    StrippedWarpedStem,
    StructureBlock,
    StructureVoid,
    Sugar,
    SugarCane,
    Sunflower,
    SuspiciousStew,
    SweetBerries,
    TallGrass,
    Target,
    Terracotta,
    TintedGlass,
    TippedArrow,
    Tnt,
    TntMinecart,
    Torch,
    TotemOfUndying,
    TraderLlamaSpawnEgg,
    TrappedChest,
    Trident,
    TripwireHook,
    TropicalFish,
    TropicalFishBucket,
    TropicalFishSpawnEgg,
    TubeCoral,
    TubeCoralBlock,
    TubeCoralFan,
    Tuff,
    TurtleEgg,
    TurtleHelmet,
    TurtleSpawnEgg,
    TwistingVines,
    VexSpawnEgg,
    VillagerSpawnEgg,
    VindicatorSpawnEgg,
    Vine,
    WanderingTraderSpawnEgg,
    WarpedButton,
    WarpedDoor,
    WarpedFence,
    WarpedFenceGate,
    WarpedFungus,
    WarpedFungusOnAStick,
    WarpedHyphae,
    WarpedNylium,
    WarpedPlanks,
    WarpedPressurePlate,
    WarpedRoots,
    WarpedSign,
    WarpedSlab,
    WarpedStairs,
    WarpedStem,
    WarpedTrapdoor,
    WarpedWartBlock,
    WaterBucket,
    WaxedCopperBlock,
    WaxedCutCopper,
    WaxedCutCopperSlab,
    WaxedCutCopperStairs,
    WaxedExposedCopper,
    WaxedExposedCutCopper,
    WaxedExposedCutCopperSlab,
    WaxedExposedCutCopperStairs,
    WaxedOxidizedCopper,
    WaxedOxidizedCutCopper,
    WaxedOxidizedCutCopperSlab,
    WaxedOxidizedCutCopperStairs,
    WaxedWeatheredCopper,
    WaxedWeatheredCutCopper,
    WaxedWeatheredCutCopperSlab,
    WaxedWeatheredCutCopperStairs,
    WeatheredCopper,
    WeatheredCutCopper,
    WeatheredCutCopperSlab,
    WeatheredCutCopperStairs,
    WeepingVines,
    WetSponge,
    Wheat,
    WheatSeeds,
    WhiteBanner,
    WhiteBed,
    WhiteCandle,
    WhiteCarpet,
    WhiteConcrete,
    WhiteConcretePowder,
    WhiteDye,
    WhiteGlazedTerracotta,
    WhiteShulkerBox,
    WhiteStainedGlass,
    WhiteStainedGlassPane,
    WhiteTerracotta,
    WhiteTulip,
    WhiteWool,
    WitchSpawnEgg,
    WitherRose,
    WitherSkeletonSkull,
    WitherSkeletonSpawnEgg,
    WolfSpawnEgg,
    WoodenAxe,
    WoodenHoe,
    WoodenPickaxe,
    WoodenShovel,
    WoodenSword,
    WritableBook,
    WrittenBook,
    YellowBanner,
    YellowBed,
    YellowCandle,
    YellowCarpet,
    YellowConcrete,
    YellowConcretePowder,
    YellowDye,
    YellowGlazedTerracotta,
    YellowShulkerBox,
    YellowStainedGlass,
    YellowStainedGlassPane,
    YellowTerracotta,
    YellowWool,
    ZoglinSpawnEgg,
    ZombieHead,
    ZombieHorseSpawnEgg,
    ZombieSpawnEgg,
    ZombieVillagerSpawnEgg,
    ZombifiedPiglinSpawnEgg,
}

export type Item = {
    ItemType: ItemType;
    Count: number;
    NBT?: any
};

export type Location = {
    x: number,
    y: number,
    z: number
};

export class MapIcon {
    constructor(
        public type: MapIconType,
        public x: number,
        public z: number,
        public direction: number,
        public displayName: string
    ) { }
}

export enum MapIconType {
    White_Arrow = 0,
    Green_Arrow,
    Red_Arrow,
    Blue_Arrow,
    White_Cross,
    Red_Pointer,
    White_Circle,
    Small_White_Circle,
    Mansion,
    Temple,
    White_Banner,
    Orange_Banner,
    Magenta_Banner,
    Light_Blue_Banner,
    Yellow_Banner,
    Lime_Banner,
    Pink_Banner,
    Gray_Banner,
    Light_Gray_Banner,
    Cyan_Banner,
    Purple_Banner,
    Blue_Banner,
    Brown_Banner,
    Green_Banner,
    Red_Banner,
    Black_Banner,
    Treasure_Marker
}

export enum ProtocolVersion {
    MC_1_8_Version = 47,
    MC_1_9_Version = 107,
    MC_1_9_1_Version = 108,
    MC_1_10_Version = 210,
    MC_1_11_2_Version = 316,
    MC_1_12_Version = 335,
    MC_1_12_2_Version = 340,
    MC_1_13_Version = 393,
    MC_1_13_2_Version = 404,
    MC_1_14_Version = 477,
    MC_1_15_Version = 573,
    MC_1_15_2_Version = 578,
    MC_1_16_Version = 735,
    MC_1_16_1_Version = 736,
    MC_1_16_2_Version = 751,
    MC_1_16_3_Version = 753,
    MC_1_16_5_Version = 754,
    MC_1_17_Version = 755,
    MC_1_17_1_Version = 756,
    MC_1_18_1_Version = 757,
    MC_1_18_2_Version = 758,
    MC_1_19_Version = 759,
    MC_1_19_2_Version = 760
}

export enum WindowActionType {
    /// <summary>
    /// Left click with mouse on a slot: grab or drop a whole item stack
    /// </summary>
    LeftClick,

    /// <summary>
    /// Right click with mouse on a slot: grab half a stack or drop a single item
    /// </summary>
    RightClick,

    /// <summary>
    /// Middle click with mouse on a slot: grab a full stack from creative inventory
    /// </summary>
    MiddleClick,

    /// <summary>
    /// Shift+Left click with mouse on a slot: send a whole item stack to the hotbar or other inventory
    /// </summary>
    ShiftClick,

    /// <summary>
    /// Drop a single item on ground
    /// </summary>
    DropItem,

    /// <summary>
    /// Drop a whole item stack on ground
    /// </summary>
    DropItemStack,

    /// <summary>
    /// Start hovering slots with left button pressed: Distribute evenly the stack on hovered slots
    /// </summary>
    StartDragLeft,

    /// <summary>
    /// Start hovering slots with right button pressed: Drop one item on each hovered slot
    /// </summary>
    StartDragRight,

    /// <summary>
    /// Start hovering slots with middle button pressed: Create one item stack on each hovered slot in creative mode
    /// </summary>
    StartDragMiddle,

    /// <summary>
    /// Hover a slot to distribute evenly an item stack
    /// </summary>
    AddDragLeft,

    /// <summary>
    /// Hover a slot to drop one item from an item stack
    /// </summary>
    AddDragRight,

    /// <summary>
    /// Hover a slot to create one item stack in creative mode
    /// </summary>
    AddDragMiddle,

    /// <summary>
    /// Stop hovering slots with left button pressed
    /// </summary>
    EndDragLeft,

    /// <summary>
    /// Stop hovering slots with right button pressed
    /// </summary>
    EndDragRight,

    /// <summary>
    /// Stop hovering slots with middble button pressed
    /// </summary>
    EndDragMiddle,
}

